spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_flyhigh
spring.datasource.username=postgres
spring.datasource.password=kape12345
spring.jpa.hibernate.ddl-auto=update